spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB

file:
  profile-dir: ./files/profileImg
  thumbnail-dir: ./files/thumbnailImg

jwt:
  secretKey: "This Data Must Be Managed By Secret NOT HERE THIS IS JUST EXAMPLE"

log:
  serverName: "Rest Api Template"
  level: ERROR
  slack:
    enabled: true
    webHookUrl: ${SLACK_URL}
    channel: error-report-bot
    userName: "[API]ErrorReportBot"
  database:
    enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE