= Trainging.zip REST API Guide
Always0ne;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===

[[overview-errors]]
== 오류

에러 응답이 발생했을 때 (상태 코드 >= 400), 본문에 해당 문제를 기술한 JSON 객체가 담겨있다.
[[AuthError]]
=== Auth Error
[[E0001]]
==== Error0001
operation::0001[snippets='response-body']
[[E0002]]
==== Error0002
operation::0002[snippets='response-body']
[[E0003]]
==== Error0003
operation::0003[snippets='response-body']
[[E0004]]
==== Error0004
operation::0004[snippets='response-body']
[[E0005]]
==== Error0005
operation::0005[snippets='response-body']
[[E0006]]
==== Error0006
operation::0006[snippets='response-body']
==== Error0007
operation::0007[snippets='response-body']

[[CommunityError]]
=== Community Error
[[E1001]]
==== Error1001
operation::1001[snippets='response-body']

[[TrainingError]]
==== Training Error
[[E1101]]
===== Error1101
operation::1101[snippets='response-body']

[[CommentError]]
==== Comment Error

[[SystemError]]
=== System Error
[[E2001]]
==== Error2001
operation::2001[snippets='response-body']


[[ImageError]]
=== Image Error
[[E3001]]
==== Error3001
operation::3001[snippets='response-body']

[[E3002]]
==== Error3002
operation::3002[snippets='response-body']
[[overview-hypermedia]]
== 하이퍼미디어

본 REST API는 하이퍼미디어와 사용하며 응답에 담겨있는 리소스는 다른 리소스에 대한 링크를 가지고 있다.
응답은 http://stateless.co/hal_specification.html[Hypertext Application from resource to resource. Language (HAL)] 형식을 따른다.
링크는 `_links`라는 키로 제공한다. 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하며, 리소스에서 제공하는 링크를 사용해야 한다.


[[Service]]
== 서비스 모듈

[[Training]]
=== 트레이닝 서비스
[[upload]]
==== 트레이닝 등록

[[sendTraining]]
===== Training-S101  트레이닝 등록하기
`Post` 요청을 사용해서 트레이닝을 작성 할 수 있다.

operation::sendTraining[snippets='http-request,http-response']


[[updateTraining]]
=====  Training-S105 트레이닝 수정하기
`Put` 요청을 사용해서 트레이닝을 수정 할 수 있다.

operation::updateTraining[snippets='path-parameters,http-request,http-response']

[[deleteTraining]]
=====  Training-S106 트레이닝 삭제하기
`Delete` 요청을 사용해서 트레이닝을 삭제 할 수 있다.

operation::deleteTraining[snippets='path-parameters,http-request,http-response']


[[updateThumbnailImage]]
=====  Training-S107 썸네일 이미지 삽입
`Post` 요청을 사용해서 썸네일 이미지를 수정할 수 있다.

operation::uploadThumbnailImage[snippets='path-parameters,curl-request,http-response']

[[lists]]
==== 트레이닝 리스트 조회

[[getTrainings]]
===== Training-S201 트레이닝 검색하기
`Get` 요청을 사용해서 트레이닝 목록을 조회 할 수 있다.

operation::getTrainings[snippets='http-request,http-response']

[[searchTrainings]]
===== Training-S202 트레이닝 목록 조회
`Get` 요청을 사용해서 트레이닝을 검색 할 수 있다.

operation::searchTrainings[snippets='http-request,http-response']


[[getThumbnailImage]]
===== Training-S203 썸네일 이미지 조회
`Get` 요청을 사용해서 썸네일 이미지를 조회할 수 있다.

operation::getThumbnailImage[snippets='path-parameters,http-request']

[[dotraining]]
==== 트레이닝 하기

[[getTraining]]
===== Training-S301 트레이닝 정보 조회
`Get` 요청을 사용해서 트레이닝을 조회 할 수 있다.

operation::getTraining[snippets='path-parameters,http-request,http-response']

[[getPoses]]
===== Training-S302 트레이닝 포즈 정보 조회
`Get` 요청을 사용해서 트레이닝 포즈 데이터를 조회 할 수 있다.

operation::getPoses[snippets='http-request,http-response']

[[comment]]
==== 댓글

[[sendComment]]
===== Community-S101 댓글 작성

`Post` 요청을 사용해서 댓글을 작성 할 수 있다.

operation::sendComment[snippets='path-parameters,http-request,http-response']

[[updateComment]]
===== Community-S102 댓글 수정

`Put` 요청을 사용해서 댓글을 수정 할 수 있다.

operation::updateComment[snippets='path-parameters,http-request,http-response']

[[deleteComment]]
===== Community-S103 댓글 삭제

`Delete` 요청을 사용해서 댓글을 삭제 할 수 있다.

operation::deleteComment[snippets='path-parameters,http-request,http-response']

[[getComments]]
===== Community-S104 댓글 조회
`Get` 요청을 사용해서 댓글들을 조회할 수 있다.

operation::getComments[snippets='http-request,http-response']

[[user]]
==== 사용자 개인화 서비스

[[subscribe]]
===== User-S101 트레이너 구독하기
`Post` 요청을 사용해서 구독을 할 수 있다.

operation::subscribe[snippets='http-request,http-response']

[[unSubscribe]]
===== User-S102 트레이너 구독 취소하기
`Delete` 요청을 사용해서 구독을 취소 할 수 있다.

operation::unSubscribe[snippets='http-request,http-response']

[[getSubscribes]]
===== User-S103 구독 리스트 조회
`GET` 요청을 사용해서 구독한 리스트를 조회할 수 있다.

operation::getSubscribes[snippets='http-request,http-response']

[[likeTraining]]
===== User-S201 트레이닝 좋아요
`Post` 요청을 사용해서 좋아요를 할 수 있다.

operation::like[snippets='http-request,http-response']

[[unlikeTraining]]
===== User-S202 트레이닝 좋아요 취소하기
`Delete` 요청을 사용해서 좋아요를 취소 할 수 있다.

operation::unLike[snippets='http-request,http-response']

[[getLikes]]
===== User-S203 좋아요 한 트레이닝 조회
`GET` 사용자가 좋아요한 트레이닝 리스트를 조회할 수 있다.

operation::getLikes[snippets='http-request,http-response']

[[profile]]
==== 프로필

[[getProfile]]
===== User-S301 프로필 조회하기
`GET` 요청을 사용해서 프로필을 조회 할 수 있다.

operation::getProfile[snippets='http-request,http-response']
[[updateProfile]]
===== User-S302 프로필 업데이트 하기
`PUT` 요청을 사용해서 프로필을 수정 할 수 있다.

operation::updateProfiles[snippets='http-request,http-response']

[[updateProfileImage]]
===== User-S303 프로필 이미지 수정하기
`Post` 요청을 사용해서 프로필 이미지를 수정할 수 있다.

operation::uploadProfileImage[snippets='path-parameters,curl-request,http-response']

[[getProfileImage]]
===== User-S304 프로필 이미지 조회하기
`Get` 요청을 사용해서 프로필 이미지를 조회할 수 있다.

operation::getProfileImage[snippets='path-parameters,http-request']

[[Auth]]
== 인증 모듈

[[signup]]
=== Auth-S001 회원가입

`Post` 요청을 사용해서 회원가입을 할 수있다.

operation::signup[snippets='http-request,http-response']

[[checkid]]
=== Auth-S002 신규 아이디 중복 검사

`Get` 요청을 사용해서 아이디 중복확인을 할 수있다.

operation::idcheck[snippets='http-request,http-response']

[[checkNickname]]
=== Auth-S003 닉네임 중복 검사

`Get` 요청을 사용해서 닉네임 중복확인을 할 수있다.

operation::nickNamecheck[snippets='http-request,http-response']

[[signin]]
=== Auth-S004 로그인

`Post` 요청을 사용해서 인증할수있다.

operation::signin[snippets='http-request,http-response']

[[refresh]]
=== Auth-S005 토큰 갱신
`Post` 요청을 사용해서 토큰을 재발급받을 수 있다.

operation::refresh[snippets='http-request,http-response']